version: '3'
services:
  apache-php:
    working_dir: /var/www/html/source
    build:
      context: ./docker/apache-php
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      vpcbr:
        ipv4_address: 10.2.1.3

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.2.1.8
    environment:
      MYSQL_ROOT_PASSWORD: asdhkjhas7698kjGdg
      MYSQL_DATABASE: toxid_01
      MYSQL_USER: toxid
      MYSQL_PASSWORD: bKJjhvDbbhjgsdkj679

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.1.0/16
